create table if not exists public.places (
  id bigint generated by default as identity primary key,
  name text not null,
  address text,
  google_maps_url text not null,
  place_id text,
  google_place_token text,
  google_internal_ids text,
  source_list_url text,
  latitude double precision not null,
  longitude double precision not null,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.itinerary_items (
  id bigint generated by default as identity primary key,
  place_id bigint not null references public.places(id) on delete cascade,
  visit_date text,
  visit_time text,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.route_segments (
  id bigint generated by default as identity primary key,
  from_item_id bigint not null references public.itinerary_items(id) on delete cascade,
  to_item_id bigint not null references public.itinerary_items(id) on delete cascade,
  mode text not null default 'walking' check (mode in ('walking', 'transit', 'bicycling', 'driving')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.route_geometry_cache (
  cache_key text primary key,
  from_place_id bigint not null references public.places(id) on delete cascade,
  to_place_id bigint not null references public.places(id) on delete cascade,
  mode text not null check (mode in ('walking', 'transit', 'bicycling', 'driving')),
  from_latitude double precision not null,
  from_longitude double precision not null,
  to_latitude double precision not null,
  to_longitude double precision not null,
  status text not null check (status in ('ok', 'no_route')),
  encoded_polyline text,
  duration_seconds integer,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.route_geometry_cache
  add column if not exists duration_seconds integer;

create index if not exists idx_itinerary_items_visit_date_time
  on public.itinerary_items (visit_date, visit_time, place_id);

create index if not exists idx_route_segments_from_to
  on public.route_segments (from_item_id, to_item_id);

create index if not exists idx_route_geometry_cache_places
  on public.route_geometry_cache (from_place_id, to_place_id, mode);

grant usage on schema public to service_role;
grant all on all tables in schema public to service_role;
grant usage, select on all sequences in schema public to service_role;

create or replace function public.reset_trip_planner_id_sequences()
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  perform setval(pg_get_serial_sequence('public.places', 'id'), coalesce((select max(id) from public.places), 1), true);
  perform setval(pg_get_serial_sequence('public.itinerary_items', 'id'), coalesce((select max(id) from public.itinerary_items), 1), true);
  perform setval(pg_get_serial_sequence('public.route_segments', 'id'), coalesce((select max(id) from public.route_segments), 1), true);
end;
$$;

grant execute on function public.reset_trip_planner_id_sequences() to service_role;

alter table public.places enable row level security;
alter table public.itinerary_items enable row level security;
alter table public.route_segments enable row level security;
alter table public.route_geometry_cache enable row level security;
