create table if not exists public.trips (
  id bigint generated by default as identity primary key,
  created_by uuid references auth.users(id) on delete set null,
  name text not null,
  destination text not null,
  destination_slug text,
  start_date date,
  end_date date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint trips_date_range_valid check (
    start_date is null or end_date is null or start_date <= end_date
  ),
  constraint trips_destination_not_blank check (btrim(destination) <> ''),
  constraint trips_destination_slug_not_blank check (
    destination_slug is null or btrim(destination_slug) <> ''
  )
);

alter table public.trips
  add column if not exists destination text;

alter table public.trips
  add column if not exists destination_slug text;

alter table public.trips
  drop constraint if exists trips_timezone_not_blank;

alter table public.trips
  drop column if exists timezone;

alter table public.trips
  alter column destination set not null;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'trips_destination_not_blank'
      and conrelid = 'public.trips'::regclass
  ) then
    alter table public.trips
      add constraint trips_destination_not_blank
      check (btrim(destination) <> '');
  end if;
end;
$$;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'trips_destination_slug_not_blank'
      and conrelid = 'public.trips'::regclass
  ) then
    alter table public.trips
      add constraint trips_destination_slug_not_blank
      check (destination_slug is null or btrim(destination_slug) <> '');
  end if;
end;
$$;

with curated_destinations(slug, name) as (
  values
    ('amsterdam', 'Amsterdam'),
    ('athens', 'Athens'),
    ('banff-national-park', 'Banff National Park'),
    ('bangkok', 'Bangkok'),
    ('barcelona', 'Barcelona'),
    ('beijing', 'Beijing'),
    ('berlin', 'Berlin'),
    ('buenos-aires', 'Buenos Aires'),
    ('cairo', 'Cairo'),
    ('calgary', 'Calgary'),
    ('cancun', 'Cancun'),
    ('cape-town', 'Cape Town'),
    ('chicago', 'Chicago'),
    ('copenhagen', 'Copenhagen'),
    ('doha', 'Doha'),
    ('dubai', 'Dubai'),
    ('dublin', 'Dublin'),
    ('edinburgh', 'Edinburgh'),
    ('florence', 'Florence'),
    ('hanoi', 'Hanoi'),
    ('ho-chi-minh-city', 'Ho Chi Minh City'),
    ('hong-kong', 'Hong Kong'),
    ('honolulu', 'Honolulu'),
    ('istanbul', 'Istanbul'),
    ('kuala-lumpur', 'Kuala Lumpur'),
    ('kyoto', 'Kyoto'),
    ('las-vegas', 'Las Vegas'),
    ('lisbon', 'Lisbon'),
    ('london', 'London'),
    ('los-angeles', 'Los Angeles'),
    ('madrid', 'Madrid'),
    ('marrakech', 'Marrakech'),
    ('mexico-city', 'Mexico City'),
    ('miami', 'Miami'),
    ('milan', 'Milan'),
    ('montreal', 'Montreal'),
    ('munich', 'Munich'),
    ('new-york-city', 'New York City'),
    ('osaka', 'Osaka'),
    ('paris', 'Paris'),
    ('prague', 'Prague'),
    ('quebec-city', 'Quebec City'),
    ('reykjavik', 'Reykjavik'),
    ('rio-de-janeiro', 'Rio de Janeiro'),
    ('rome', 'Rome'),
    ('san-francisco', 'San Francisco'),
    ('seoul', 'Seoul'),
    ('singapore', 'Singapore'),
    ('sydney', 'Sydney'),
    ('taipei', 'Taipei'),
    ('tokyo', 'Tokyo'),
    ('toronto', 'Toronto'),
    ('vancouver', 'Vancouver'),
    ('venice', 'Venice'),
    ('victoria', 'Victoria, BC'),
    ('vienna', 'Vienna'),
    ('washington-dc', 'Washington, DC'),
    ('zurich', 'Zurich')
)
update public.trips
set destination_slug = curated_destinations.slug
from curated_destinations
where public.trips.destination_slug is null
  and (
    lower(btrim(public.trips.destination)) = lower(curated_destinations.name)
    or lower(btrim(public.trips.destination)) = lower(curated_destinations.slug)
  );

create table if not exists public.trip_memberships (
  trip_id bigint not null references public.trips(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null check (role in ('owner', 'editor', 'viewer')),
  created_at timestamptz not null default now(),
  primary key (trip_id, user_id)
);

create table if not exists public.places (
  id bigint generated by default as identity primary key,
  trip_id bigint not null references public.trips(id) on delete cascade,
  name text not null,
  address text,
  google_maps_url text not null,
  place_id text,
  google_place_token text,
  google_internal_ids text,
  source_list_url text,
  latitude double precision not null,
  longitude double precision not null,
  notes text,
  links text[] not null default '{}',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.places
  add column if not exists links text[] not null default '{}';

alter table public.places
  add column if not exists trip_id bigint references public.trips(id) on delete cascade;

create table if not exists public.itinerary_items (
  id bigint generated by default as identity primary key,
  trip_id bigint not null references public.trips(id) on delete cascade,
  place_id bigint not null references public.places(id) on delete cascade,
  visit_date text,
  visit_time text,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.itinerary_items
  add column if not exists trip_id bigint references public.trips(id) on delete cascade;

create table if not exists public.route_segments (
  id bigint generated by default as identity primary key,
  trip_id bigint not null references public.trips(id) on delete cascade,
  from_item_id bigint not null references public.itinerary_items(id) on delete cascade,
  to_item_id bigint not null references public.itinerary_items(id) on delete cascade,
  mode text not null default 'walking' check (mode in ('walking', 'transit', 'bicycling', 'driving')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.route_segments
  add column if not exists trip_id bigint references public.trips(id) on delete cascade;

create table if not exists public.route_geometry_cache (
  cache_key text primary key,
  from_place_id bigint not null references public.places(id) on delete cascade,
  to_place_id bigint not null references public.places(id) on delete cascade,
  mode text not null check (mode in ('walking', 'transit', 'bicycling', 'driving')),
  from_latitude double precision not null,
  from_longitude double precision not null,
  to_latitude double precision not null,
  to_longitude double precision not null,
  status text not null check (status in ('ok', 'no_route')),
  encoded_polyline text,
  duration_seconds integer,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.route_geometry_cache
  add column if not exists duration_seconds integer;

create index if not exists idx_itinerary_items_visit_date_time
  on public.itinerary_items (trip_id, visit_date, visit_time, place_id);

drop index if exists public.idx_route_segments_from_to;

with ranked_route_segments as (
  select
    id,
    row_number() over (
      partition by trip_id, from_item_id, to_item_id
      order by id
    ) as duplicate_rank
  from public.route_segments
)
delete from public.route_segments
using ranked_route_segments
where public.route_segments.id = ranked_route_segments.id
  and ranked_route_segments.duplicate_rank > 1;

create unique index if not exists idx_route_segments_trip_pair_unique
  on public.route_segments (trip_id, from_item_id, to_item_id);

create index if not exists idx_route_geometry_cache_places
  on public.route_geometry_cache (from_place_id, to_place_id, mode);

create index if not exists idx_places_trip_name
  on public.places (trip_id, name);

create index if not exists idx_trip_memberships_user
  on public.trip_memberships (user_id, trip_id);

grant usage on schema public to service_role;
grant all on all tables in schema public to service_role;
grant usage, select on all sequences in schema public to service_role;

create or replace function public.reconcile_route_segments_for_trip(p_trip_id bigint)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  perform pg_advisory_xact_lock(
    hashtextextended('route_segments', p_trip_id)
  );

  with routable_items as (
    select
      itinerary_items.id,
      lead(itinerary_items.id) over (
        partition by itinerary_items.visit_date
        order by
          split_part(itinerary_items.visit_time, ':', 1)::integer * 60
            + split_part(itinerary_items.visit_time, ':', 2)::integer,
          lower(places.name),
          places.name,
          itinerary_items.place_id
      ) as to_item_id
    from public.itinerary_items
    join public.places
      on places.id = itinerary_items.place_id
      and places.trip_id = itinerary_items.trip_id
    where itinerary_items.trip_id = p_trip_id
      and itinerary_items.visit_date is not null
      and itinerary_items.visit_date <> ''
      and itinerary_items.visit_time is not null
      and itinerary_items.visit_time ~ '^[0-9]{1,2}:[0-9]{2}$'
      and split_part(itinerary_items.visit_time, ':', 1)::integer between 0 and 23
      and split_part(itinerary_items.visit_time, ':', 2)::integer between 0 and 59
  ),
  desired_pairs as (
    select
      id as from_item_id,
      to_item_id
    from routable_items
    where to_item_id is not null
  ),
  ranked_existing_segments as (
    select
      route_segments.id,
      desired_pairs.from_item_id is not null as is_desired,
      row_number() over (
        partition by route_segments.from_item_id, route_segments.to_item_id
        order by route_segments.id
      ) as duplicate_rank
    from public.route_segments
    left join desired_pairs
      on desired_pairs.from_item_id = route_segments.from_item_id
      and desired_pairs.to_item_id = route_segments.to_item_id
    where route_segments.trip_id = p_trip_id
  )
  delete from public.route_segments
  where id in (
    select id
    from ranked_existing_segments
    where not is_desired
      or duplicate_rank > 1
  );

  with routable_items as (
    select
      itinerary_items.id,
      lead(itinerary_items.id) over (
        partition by itinerary_items.visit_date
        order by
          split_part(itinerary_items.visit_time, ':', 1)::integer * 60
            + split_part(itinerary_items.visit_time, ':', 2)::integer,
          lower(places.name),
          places.name,
          itinerary_items.place_id
      ) as to_item_id
    from public.itinerary_items
    join public.places
      on places.id = itinerary_items.place_id
      and places.trip_id = itinerary_items.trip_id
    where itinerary_items.trip_id = p_trip_id
      and itinerary_items.visit_date is not null
      and itinerary_items.visit_date <> ''
      and itinerary_items.visit_time is not null
      and itinerary_items.visit_time ~ '^[0-9]{1,2}:[0-9]{2}$'
      and split_part(itinerary_items.visit_time, ':', 1)::integer between 0 and 23
      and split_part(itinerary_items.visit_time, ':', 2)::integer between 0 and 59
  ),
  desired_pairs as (
    select
      id as from_item_id,
      to_item_id
    from routable_items
    where to_item_id is not null
  )
  insert into public.route_segments (trip_id, from_item_id, to_item_id, mode)
  select
    p_trip_id,
    desired_pairs.from_item_id,
    desired_pairs.to_item_id,
    'walking'
  from desired_pairs
  where not exists (
    select 1
    from public.route_segments
    where route_segments.trip_id = p_trip_id
      and route_segments.from_item_id = desired_pairs.from_item_id
      and route_segments.to_item_id = desired_pairs.to_item_id
  )
  on conflict (trip_id, from_item_id, to_item_id) do nothing;
end;
$$;

revoke all on function public.reconcile_route_segments_for_trip(bigint) from public;
grant execute on function public.reconcile_route_segments_for_trip(bigint) to service_role;

create or replace function public.reset_trip_planner_id_sequences()
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  perform setval(pg_get_serial_sequence('public.trips', 'id'), coalesce((select max(id) from public.trips), 1), true);
  perform setval(pg_get_serial_sequence('public.places', 'id'), coalesce((select max(id) from public.places), 1), true);
  perform setval(pg_get_serial_sequence('public.itinerary_items', 'id'), coalesce((select max(id) from public.itinerary_items), 1), true);
  perform setval(pg_get_serial_sequence('public.route_segments', 'id'), coalesce((select max(id) from public.route_segments), 1), true);
end;
$$;

grant execute on function public.reset_trip_planner_id_sequences() to service_role;

alter table public.places enable row level security;
alter table public.itinerary_items enable row level security;
alter table public.route_segments enable row level security;
alter table public.route_geometry_cache enable row level security;
alter table public.trips enable row level security;
alter table public.trip_memberships enable row level security;
