import { AI_INTEREST_TAG_OPTIONS } from "@/lib/ai-planning-preferences";
import { straightLineDistanceKm } from "@/lib/geo-distance";
import type {
  AiIndoorOutdoor,
  AiRegionDistanceTier,
  AiTransitHubType,
} from "@/lib/types";

import { AiUpstreamRateLimitError } from "./errors";
import {
  extractOutputText,
  openAiFailureDetail,
  openAiRetryAfterSeconds,
  openAiUsageTokens,
} from "./openai-response";

// How many attractions the model is asked to produce for a destination.
export const AI_CATALOG_TARGET_CANDIDATE_COUNT = 40;
// A generated catalog with fewer usable attractions than this is rejected so a
// degenerate model response never becomes a destination's permanent catalog.
export const AI_CATALOG_MIN_CANDIDATE_COUNT = 12;
// Generated coordinates farther than this from the destination center are
// treated as hallucinated and dropped. Generous so day-trip candidates survive.
export const AI_CATALOG_MAX_DISTANCE_KM = 400;
// Transit hubs are a short, stable list generated by their own small call so
// the wizard's Start & end step unlocks in a few seconds while the attraction
// catalog is still being generated.
export const AI_CATALOG_TARGET_HUB_COUNT = 5;

const OPENAI_RESPONSES_ENDPOINT = "https://api.openai.com/v1/responses";

const AI_INTEREST_TAG_VALUES = AI_INTEREST_TAG_OPTIONS.map(
  (option) => option.value,
);
const AI_INTEREST_TAG_SET = new Set<string>(AI_INTEREST_TAG_VALUES);
const REGION_DISTANCE_TIERS: AiRegionDistanceTier[] = [
  "central",
  "nearby",
  "day_trip",
];
const INDOOR_OUTDOOR_VALUES: AiIndoorOutdoor[] = [
  "indoor",
  "outdoor",
  "mixed",
];
const TRANSIT_HUB_TYPES: AiTransitHubType[] = [
  "airport",
  "train_station",
  "bus_terminal",
  "ferry_terminal",
];

export type AiCatalogDestination = {
  name: string;
  latitude: number | null;
  longitude: number | null;
  countryNames: string[];
};

export type AiDestinationCatalog = {
  candidates: Array<{
    name: string;
    category: string;
    tags: string[];
    area: string | null;
    region_distance_tier: AiRegionDistanceTier;
    latitude: number;
    longitude: number;
    typical_duration_minutes: number;
    indoor_outdoor: AiIndoorOutdoor | null;
    planning_note: string | null;
    blurb: string | null;
  }>;
};

export type AiDestinationTransitHubList = {
  transit_hubs: Array<{
    name: string;
    hub_type: AiTransitHubType;
    iata_code: string | null;
    latitude: number;
    longitude: number;
  }>;
};

export type SanitizedCatalogCandidate =
  AiDestinationCatalog["candidates"][number] & { sort_order: number };

export type SanitizedCatalogHub =
  AiDestinationTransitHubList["transit_hubs"][number] & { sort_order: number };

type RequestUsage = {
  inputTokens: number | null;
  outputTokens: number | null;
};

type RequestOptions = {
  apiKey: string;
  model: string;
  destination: AiCatalogDestination;
  fetchImpl?: typeof fetch;
};

const CATALOG_SYSTEM_PROMPT = [
  `Build a catalog of roughly ${AI_CATALOG_TARGET_CANDIDATE_COUNT} attractions for the given travel destination, for use by an itinerary planner.`,
  "Order the candidates by how famous and essential they are, most iconic first.",
  // No web search here: this call must be fast, and long-established
  // attractions are stable knowledge. Date-specific operation and opening
  // hours are verified later, at itinerary generation.
  "Rely on your own knowledge; exclude attractions you know to be permanently closed or under long-term renovation.",
  "Include attractions, sights, parks, museums, viewpoints, neighborhoods, and markets or food halls; do not include restaurants, cafes, bars, or hotels.",
  "Cover a diverse mix across the provided interest tags and across central, nearby, and day_trip distance tiers, weighted toward central.",
  "Coordinates must be the attraction's real location in decimal degrees, as precise as you can give.",
  "typical_duration_minutes is the usual visit length. planning_note is a short practical tip such as booking requirements, or null. blurb is one enticing sentence, or null.",
  "area is the neighborhood or district name, or null.",
].join(" ");

const TRANSIT_HUBS_SYSTEM_PROMPT = [
  `List the main arrival transit hubs (airports, train stations, bus terminals, ferry terminals) travelers use for the given destination, largest and most used first, up to ${AI_CATALOG_TARGET_HUB_COUNT}.`,
  "Coordinates must be the hub's real location in decimal degrees.",
  "iata_code is the airport's IATA code, or null for non-airport hubs.",
].join(" ");

export async function requestAiDestinationCatalog({
  apiKey,
  model,
  destination,
  fetchImpl = fetch,
}: RequestOptions): Promise<{
  catalog: AiDestinationCatalog;
  usage: RequestUsage;
}> {
  const { parsed, usage } = await requestStructuredOpenAiResponse({
    apiKey,
    model,
    fetchImpl,
    failurePrefix: "OpenAI destination catalog generation failed",
    payload: {
      model,
      input: promptInput(CATALOG_SYSTEM_PROMPT, {
        destination: destinationPromptContext(destination),
        interest_tags: AI_INTEREST_TAG_VALUES,
      }),
      text: structuredTextFormat(
        "ai_destination_catalog",
        AI_DESTINATION_CATALOG_SCHEMA,
      ),
    },
  });

  return { catalog: parsed as AiDestinationCatalog, usage };
}

export async function requestAiDestinationTransitHubs({
  apiKey,
  model,
  destination,
  fetchImpl = fetch,
}: RequestOptions): Promise<{
  hubList: AiDestinationTransitHubList;
  usage: RequestUsage;
}> {
  const { parsed, usage } = await requestStructuredOpenAiResponse({
    apiKey,
    model,
    fetchImpl,
    failurePrefix: "OpenAI transit hub generation failed",
    payload: {
      model,
      input: promptInput(TRANSIT_HUBS_SYSTEM_PROMPT, {
        destination: destinationPromptContext(destination),
      }),
      text: structuredTextFormat(
        "ai_destination_transit_hubs",
        AI_DESTINATION_TRANSIT_HUBS_SCHEMA,
      ),
    },
  });

  return { hubList: parsed as AiDestinationTransitHubList, usage };
}

async function requestStructuredOpenAiResponse({
  apiKey,
  fetchImpl,
  failurePrefix,
  payload,
}: {
  apiKey: string;
  model: string;
  fetchImpl: typeof fetch;
  failurePrefix: string;
  payload: Record<string, unknown>;
}): Promise<{ parsed: unknown; usage: RequestUsage }> {
  const response = await fetchImpl(OPENAI_RESPONSES_ENDPOINT, {
    method: "POST",
    headers: {
      authorization: `Bearer ${apiKey}`,
      "content-type": "application/json",
    },
    body: JSON.stringify(payload),
  });
  // OpenAI errors can arrive as HTML gateway pages, so parse defensively.
  const body: unknown = await response.json().catch(() => null);

  if (response.status === 429) {
    throw new AiUpstreamRateLimitError(
      openAiFailureDetail(body, response.status),
      openAiRetryAfterSeconds(response, body),
    );
  }
  if (!response.ok || body === null) {
    throw new Error(
      `${failurePrefix}: ${openAiFailureDetail(body, response.status)}`,
    );
  }

  return {
    parsed: JSON.parse(extractOutputText(body)),
    usage: openAiUsageTokens(body),
  };
}

function destinationPromptContext(destination: AiCatalogDestination) {
  return {
    name: destination.name,
    latitude: destination.latitude,
    longitude: destination.longitude,
    countries: destination.countryNames,
  };
}

function promptInput(systemPrompt: string, userContext: unknown) {
  return [
    {
      role: "system",
      content: [{ type: "input_text", text: systemPrompt }],
    },
    {
      role: "user",
      content: [{ type: "input_text", text: JSON.stringify(userContext) }],
    },
  ];
}

function structuredTextFormat(name: string, schema: unknown) {
  return {
    format: {
      type: "json_schema",
      name,
      strict: true,
      schema,
    },
  };
}

/**
 * Filters generated attractions down to rows that satisfy the candidate
 * table's constraints: deduped names, known tags/tiers, valid coordinates near
 * the destination, positive durations. Throws when too few candidates survive
 * so a bad generation is retried later instead of being persisted.
 */
export function sanitizeAiDestinationCandidates(
  catalog: AiDestinationCatalog,
  destination: Pick<AiCatalogDestination, "latitude" | "longitude">,
): SanitizedCatalogCandidate[] {
  const seenCandidateNames = new Set<string>();
  const candidates: SanitizedCatalogCandidate[] = [];

  for (const candidate of catalog.candidates) {
    const name = candidate.name.trim();
    const category = candidate.category.trim();
    if (!name || !category) continue;
    if (seenCandidateNames.has(name.toLowerCase())) continue;
    if (!isUsableLocation(candidate, destination)) continue;
    if (
      !Number.isInteger(candidate.typical_duration_minutes) ||
      candidate.typical_duration_minutes <= 0
    ) {
      continue;
    }

    seenCandidateNames.add(name.toLowerCase());
    candidates.push({
      ...candidate,
      name,
      category,
      tags: unique(candidate.tags.filter((tag) => AI_INTEREST_TAG_SET.has(tag))),
      area: trimmedOrNull(candidate.area),
      region_distance_tier: REGION_DISTANCE_TIERS.includes(
        candidate.region_distance_tier,
      )
        ? candidate.region_distance_tier
        : "central",
      indoor_outdoor:
        candidate.indoor_outdoor !== null &&
        INDOOR_OUTDOOR_VALUES.includes(candidate.indoor_outdoor)
          ? candidate.indoor_outdoor
          : null,
      planning_note: trimmedOrNull(candidate.planning_note),
      blurb: trimmedOrNull(candidate.blurb),
      sort_order: candidates.length + 1,
    });
  }

  if (candidates.length < AI_CATALOG_MIN_CANDIDATE_COUNT) {
    throw new Error(
      `AI destination catalog produced only ${candidates.length} usable candidates.`,
    );
  }

  return candidates;
}

// Hubs have no minimum count: a destination with no usable hubs simply offers
// the Google-Maps-URL entry path in the wizard instead.
export function sanitizeAiDestinationTransitHubs(
  hubList: AiDestinationTransitHubList,
  destination: Pick<AiCatalogDestination, "latitude" | "longitude">,
): SanitizedCatalogHub[] {
  const seenHubNames = new Set<string>();
  const transitHubs: SanitizedCatalogHub[] = [];

  for (const hub of hubList.transit_hubs) {
    const name = hub.name.trim();
    if (!name || seenHubNames.has(name.toLowerCase())) continue;
    if (!TRANSIT_HUB_TYPES.includes(hub.hub_type)) continue;
    if (!isUsableLocation(hub, destination)) continue;

    seenHubNames.add(name.toLowerCase());
    transitHubs.push({
      ...hub,
      name,
      iata_code: trimmedOrNull(hub.iata_code),
      sort_order: transitHubs.length + 1,
    });
  }

  return transitHubs;
}

function isUsableLocation(
  location: { latitude: number; longitude: number },
  destination: Pick<AiCatalogDestination, "latitude" | "longitude">,
): boolean {
  if (
    typeof location.latitude !== "number" ||
    typeof location.longitude !== "number" ||
    !Number.isFinite(location.latitude) ||
    !Number.isFinite(location.longitude) ||
    Math.abs(location.latitude) > 90 ||
    Math.abs(location.longitude) > 180
  ) {
    return false;
  }
  if (destination.latitude === null || destination.longitude === null) {
    return true;
  }

  return (
    straightLineDistanceKm(
      { latitude: destination.latitude, longitude: destination.longitude },
      location,
    ) <= AI_CATALOG_MAX_DISTANCE_KM
  );
}

function trimmedOrNull(value: string | null): string | null {
  const trimmed = value?.trim();
  return trimmed ? trimmed : null;
}

function unique<T>(values: T[]): T[] {
  return Array.from(new Set(values));
}

const AI_DESTINATION_CATALOG_SCHEMA = {
  type: "object",
  additionalProperties: false,
  required: ["candidates"],
  properties: {
    candidates: {
      type: "array",
      items: {
        type: "object",
        additionalProperties: false,
        required: [
          "name",
          "category",
          "tags",
          "area",
          "region_distance_tier",
          "latitude",
          "longitude",
          "typical_duration_minutes",
          "indoor_outdoor",
          "planning_note",
          "blurb",
        ],
        properties: {
          name: { type: "string" },
          category: { type: "string" },
          tags: {
            type: "array",
            items: { type: "string", enum: AI_INTEREST_TAG_VALUES },
          },
          area: { type: ["string", "null"] },
          region_distance_tier: {
            type: "string",
            enum: REGION_DISTANCE_TIERS,
          },
          latitude: { type: "number" },
          longitude: { type: "number" },
          typical_duration_minutes: { type: "integer" },
          indoor_outdoor: {
            type: ["string", "null"],
            enum: [...INDOOR_OUTDOOR_VALUES, null],
          },
          planning_note: { type: ["string", "null"] },
          blurb: { type: ["string", "null"] },
        },
      },
    },
  },
};

const AI_DESTINATION_TRANSIT_HUBS_SCHEMA = {
  type: "object",
  additionalProperties: false,
  required: ["transit_hubs"],
  properties: {
    transit_hubs: {
      type: "array",
      items: {
        type: "object",
        additionalProperties: false,
        required: ["name", "hub_type", "iata_code", "latitude", "longitude"],
        properties: {
          name: { type: "string" },
          hub_type: { type: "string", enum: TRANSIT_HUB_TYPES },
          iata_code: { type: ["string", "null"] },
          latitude: { type: "number" },
          longitude: { type: "number" },
        },
      },
    },
  },
};
