create table if not exists public.ai_destination_candidates (
  id bigint generated by default as identity primary key,
  destination_slug text not null,
  name text not null,
  category text not null,
  tags text[] not null default '{}',
  area text,
  region_distance_tier text not null default 'central',
  sort_order integer not null,
  latitude double precision not null,
  longitude double precision not null,
  google_place_id text,
  typical_duration_minutes integer not null,
  indoor_outdoor text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint ai_destination_candidates_destination_slug_not_blank
    check (btrim(destination_slug) <> ''),
  constraint ai_destination_candidates_name_not_blank
    check (btrim(name) <> ''),
  constraint ai_destination_candidates_category_not_blank
    check (btrim(category) <> ''),
  constraint ai_destination_candidates_region_distance_tier_valid
    check (region_distance_tier in ('central', 'nearby', 'day_trip')),
  constraint ai_destination_candidates_sort_order_positive
    check (sort_order > 0),
  constraint ai_destination_candidates_latitude_valid
    check (latitude between -90 and 90),
  constraint ai_destination_candidates_longitude_valid
    check (longitude between -180 and 180),
  constraint ai_destination_candidates_duration_positive
    check (typical_duration_minutes > 0),
  constraint ai_destination_candidates_indoor_outdoor_valid
    check (indoor_outdoor is null or indoor_outdoor in ('indoor', 'outdoor', 'mixed'))
);

create unique index if not exists idx_ai_destination_candidates_slug_sort
  on public.ai_destination_candidates (destination_slug, sort_order);

create unique index if not exists idx_ai_destination_candidates_slug_name
  on public.ai_destination_candidates (destination_slug, lower(name));

create index if not exists idx_ai_destination_candidates_slug_area
  on public.ai_destination_candidates (destination_slug, area);

create table if not exists public.trip_lodgings (
  id bigint generated by default as identity primary key,
  trip_id bigint not null references public.trips(id) on delete cascade,
  name text not null,
  address text,
  latitude double precision not null,
  longitude double precision not null,
  google_place_id text,
  check_in_date date,
  check_out_date date,
  is_primary boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint trip_lodgings_name_not_blank
    check (btrim(name) <> ''),
  constraint trip_lodgings_latitude_valid
    check (latitude between -90 and 90),
  constraint trip_lodgings_longitude_valid
    check (longitude between -180 and 180),
  constraint trip_lodgings_date_range_valid
    check (
      check_in_date is null
      or check_out_date is null
      or check_in_date <= check_out_date
    )
);

create unique index if not exists idx_trip_lodgings_primary_unique
  on public.trip_lodgings (trip_id)
  where is_primary;

create index if not exists idx_trip_lodgings_trip_id
  on public.trip_lodgings (trip_id);

create table if not exists public.ai_planning_preferences (
  trip_id bigint primary key references public.trips(id) on delete cascade,
  visits_per_day_min smallint not null default 2,
  visits_per_day_max smallint not null default 3,
  interest_tags text[] not null default '{}',
  preferred_travel_modes text[] not null default '{walking,transit}',
  must_see_candidate_ids bigint[] not null default '{}',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint ai_planning_preferences_visit_range_valid
    check (
      visits_per_day_min between 1 and 4
      and visits_per_day_max between 1 and 4
      and visits_per_day_min <= visits_per_day_max
    ),
  constraint ai_planning_preferences_travel_modes_valid
    check (
      preferred_travel_modes <@ array['walking', 'transit', 'bicycling', 'driving']::text[]
      and array_length(preferred_travel_modes, 1) is not null
    )
);

create table if not exists public.ai_plan_generations (
  id bigint generated by default as identity primary key,
  trip_id bigint not null references public.trips(id) on delete cascade,
  status text not null default 'running',
  model text,
  prompt_version text not null,
  preferences_snapshot jsonb not null default '{}'::jsonb,
  candidate_count integer not null default 0,
  must_see_count integer not null default 0,
  primary_validation_status text,
  primary_validation_errors jsonb not null default '[]'::jsonb,
  repair_attempted boolean not null default false,
  repair_validation_status text,
  repair_validation_errors jsonb not null default '[]'::jsonb,
  generated_place_count integer not null default 0,
  generated_day_count integer not null default 0,
  duration_ms integer,
  token_input_count integer,
  token_output_count integer,
  failure_reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint ai_plan_generations_status_valid
    check (status in ('running', 'completed', 'failed')),
  constraint ai_plan_generations_primary_validation_status_valid
    check (
      primary_validation_status is null
      or primary_validation_status in ('valid', 'invalid')
    ),
  constraint ai_plan_generations_repair_validation_status_valid
    check (
      repair_validation_status is null
      or repair_validation_status in ('valid', 'invalid', 'not_attempted')
    ),
  constraint ai_plan_generations_counts_non_negative
    check (
      candidate_count >= 0
      and must_see_count >= 0
      and generated_place_count >= 0
      and generated_day_count >= 0
    ),
  constraint ai_plan_generations_duration_non_negative
    check (duration_ms is null or duration_ms >= 0),
  constraint ai_plan_generations_tokens_non_negative
    check (
      (token_input_count is null or token_input_count >= 0)
      and (token_output_count is null or token_output_count >= 0)
    )
);

create index if not exists idx_ai_plan_generations_trip_created
  on public.ai_plan_generations (trip_id, created_at desc);

alter table public.places
  add column if not exists created_by_source text not null default 'manual';

alter table public.places
  add column if not exists ai_generation_id bigint
    references public.ai_plan_generations(id) on delete set null;

alter table public.itinerary_items
  add column if not exists created_by_source text not null default 'manual';

alter table public.itinerary_items
  add column if not exists ai_generation_id bigint
    references public.ai_plan_generations(id) on delete set null;

alter table public.route_segments
  add column if not exists created_by_source text not null default 'manual';

alter table public.route_segments
  add column if not exists ai_generation_id bigint
    references public.ai_plan_generations(id) on delete set null;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'places_created_by_source_valid'
      and conrelid = 'public.places'::regclass
  ) then
    alter table public.places
      add constraint places_created_by_source_valid
      check (created_by_source in ('manual', 'ai', 'import'));
  end if;
end;
$$;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'itinerary_items_created_by_source_valid'
      and conrelid = 'public.itinerary_items'::regclass
  ) then
    alter table public.itinerary_items
      add constraint itinerary_items_created_by_source_valid
      check (created_by_source in ('manual', 'ai', 'import'));
  end if;
end;
$$;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'route_segments_created_by_source_valid'
      and conrelid = 'public.route_segments'::regclass
  ) then
    alter table public.route_segments
      add constraint route_segments_created_by_source_valid
      check (created_by_source in ('manual', 'ai', 'import'));
  end if;
end;
$$;

create index if not exists idx_places_ai_generation
  on public.places (trip_id, ai_generation_id)
  where ai_generation_id is not null;

create index if not exists idx_itinerary_items_ai_generation
  on public.itinerary_items (trip_id, ai_generation_id)
  where ai_generation_id is not null;

create index if not exists idx_route_segments_ai_generation
  on public.route_segments (trip_id, ai_generation_id)
  where ai_generation_id is not null;

alter table public.ai_destination_candidates enable row level security;
alter table public.trip_lodgings enable row level security;
alter table public.ai_planning_preferences enable row level security;
alter table public.ai_plan_generations enable row level security;

grant all on public.ai_destination_candidates to service_role;
grant all on public.trip_lodgings to service_role;
grant all on public.ai_planning_preferences to service_role;
grant all on public.ai_plan_generations to service_role;

grant usage, select on sequence public.ai_destination_candidates_id_seq to service_role;
grant usage, select on sequence public.trip_lodgings_id_seq to service_role;
grant usage, select on sequence public.ai_plan_generations_id_seq to service_role;
