insert into public.ai_destination_candidates (
  destination_slug,
  name,
  category,
  tags,
  area,
  region_distance_tier,
  sort_order,
  latitude,
  longitude,
  google_place_id,
  typical_duration_minutes,
  indoor_outdoor
)
values
  ('new-york-city', 'Central Park', 'park', array['nature', 'kid-friendly', 'low-cost-free'], 'Manhattan', 'central', 1, 40.7825547, -73.9655834, null, 180, 'outdoor'),
  ('new-york-city', 'Times Square', 'landmark', array['landmarks', 'kid-friendly', 'low-cost-free'], 'Midtown Manhattan', 'central', 2, 40.7579747, -73.9855426, null, 45, 'outdoor'),
  ('new-york-city', 'Brooklyn Bridge', 'landmark', array['landmarks', 'viewpoints', 'low-cost-free'], 'Lower Manhattan and Brooklyn', 'nearby', 3, 40.7060855, -73.9968643, null, 75, 'outdoor'),
  ('new-york-city', 'Statue of Liberty', 'landmark', array['landmarks', 'viewpoints', 'kid-friendly'], 'New York Harbor', 'nearby', 4, 40.6892494, -74.0445004, null, 180, 'outdoor'),
  ('new-york-city', '9/11 Memorial and Museum', 'museum', array['museums', 'landmarks'], 'Lower Manhattan', 'central', 5, 40.7115776, -74.0133362, null, 150, 'mixed'),
  ('new-york-city', 'The Museum of Modern Art', 'museum', array['museums'], 'Midtown Manhattan', 'central', 6, 40.7614327, -73.9776216, null, 120, 'indoor'),
  ('new-york-city', 'Metropolitan Museum of Art', 'museum', array['museums', 'landmarks'], 'Upper East Side', 'central', 7, 40.7794366, -73.963244, null, 180, 'indoor'),
  ('new-york-city', 'Empire State Building', 'viewpoint', array['landmarks', 'viewpoints'], 'Midtown Manhattan', 'central', 8, 40.7484405, -73.9856644, null, 90, 'mixed'),
  ('new-york-city', 'Top of the Rock', 'viewpoint', array['landmarks', 'viewpoints'], 'Midtown Manhattan', 'central', 9, 40.7593495, -73.9794087, null, 90, 'mixed'),
  ('new-york-city', 'The High Line', 'park', array['nature', 'neighborhoods', 'low-cost-free'], 'Chelsea', 'central', 10, 40.748, -74.0048, null, 90, 'outdoor'),
  ('new-york-city', 'Grand Central Terminal', 'landmark', array['landmarks', 'low-cost-free'], 'Midtown Manhattan', 'central', 11, 40.7533582, -73.9768041, null, 45, 'indoor'),
  ('new-york-city', 'Bryant Park', 'park', array['nature', 'low-cost-free'], 'Midtown Manhattan', 'central', 12, 40.7535367, -73.9829529, null, 45, 'outdoor'),
  ('new-york-city', 'New York Public Library Stephen A. Schwarzman Building', 'landmark', array['landmarks', 'low-cost-free'], 'Midtown Manhattan', 'central', 13, 40.7531823, -73.9822534, null, 60, 'indoor'),
  ('new-york-city', 'DUMBO Manhattan Bridge View', 'viewpoint', array['viewpoints', 'neighborhoods', 'low-cost-free'], 'Brooklyn', 'nearby', 14, 40.7033165, -73.9895698, null, 45, 'outdoor'),
  ('new-york-city', 'American Museum of Natural History', 'museum', array['museums', 'kid-friendly'], 'Upper West Side', 'central', 15, 40.7813241, -73.9739882, null, 150, 'indoor'),
  ('banff-national-park', 'Lake Louise', 'scenic_lake', array['nature', 'viewpoints', 'kid-friendly'], 'Lake Louise', 'nearby', 1, 51.4165, -116.2128, null, 120, 'outdoor'),
  ('banff-national-park', 'Moraine Lake', 'scenic_lake', array['nature', 'viewpoints'], 'Lake Louise', 'nearby', 2, 51.3217, -116.186, null, 120, 'outdoor'),
  ('banff-national-park', 'Johnston Canyon', 'hike', array['nature', 'viewpoints'], 'Bow Valley Parkway', 'nearby', 3, 51.245, -115.839, null, 180, 'outdoor'),
  ('banff-national-park', 'Banff Gondola and Sulphur Mountain', 'viewpoint', array['nature', 'viewpoints', 'kid-friendly'], 'Banff Town', 'central', 4, 51.1487, -115.5554, null, 150, 'mixed'),
  ('banff-national-park', 'Bow Falls', 'viewpoint', array['nature', 'viewpoints', 'low-cost-free'], 'Banff Town', 'central', 5, 51.1667, -115.5601, null, 45, 'outdoor'),
  ('banff-national-park', 'Lake Minnewanka', 'scenic_lake', array['nature', 'viewpoints', 'kid-friendly'], 'Minnewanka Loop', 'nearby', 6, 51.2478, -115.4969, null, 120, 'outdoor'),
  ('banff-national-park', 'Two Jack Lake', 'scenic_lake', array['nature', 'viewpoints', 'low-cost-free'], 'Minnewanka Loop', 'nearby', 7, 51.2291, -115.4947, null, 60, 'outdoor'),
  ('banff-national-park', 'Cave and Basin National Historic Site', 'landmark', array['landmarks', 'museums', 'kid-friendly'], 'Banff Town', 'central', 8, 51.1697, -115.5906, null, 90, 'mixed'),
  ('banff-national-park', 'Vermilion Lakes', 'scenic_lake', array['nature', 'viewpoints', 'low-cost-free'], 'Banff Town', 'central', 9, 51.1814, -115.5949, null, 60, 'outdoor'),
  ('banff-national-park', 'Banff Avenue', 'neighborhood', array['neighborhoods', 'landmarks', 'kid-friendly'], 'Banff Town', 'central', 10, 51.1778, -115.5708, null, 75, 'outdoor'),
  ('banff-national-park', 'Hoodoos Viewpoint', 'viewpoint', array['nature', 'viewpoints', 'low-cost-free'], 'Banff Town', 'central', 11, 51.1852, -115.5379, null, 45, 'outdoor'),
  ('banff-national-park', 'Peyto Lake Viewpoint', 'viewpoint', array['nature', 'viewpoints'], 'Icefields Parkway', 'day_trip', 12, 51.7175, -116.515, null, 90, 'outdoor'),
  ('banff-national-park', 'Bow Lake', 'scenic_lake', array['nature', 'viewpoints'], 'Icefields Parkway', 'day_trip', 13, 51.679, -116.4674, null, 75, 'outdoor'),
  ('banff-national-park', 'Sunshine Meadows', 'hike', array['nature', 'viewpoints'], 'Sunshine Village', 'nearby', 14, 51.1146, -115.7674, null, 180, 'outdoor'),
  ('banff-national-park', 'Lake Louise Sightseeing Gondola', 'viewpoint', array['nature', 'viewpoints', 'kid-friendly'], 'Lake Louise', 'nearby', 15, 51.4406, -116.1627, null, 150, 'mixed'),
  ('los-angeles', 'Griffith Observatory', 'viewpoint', array['landmarks', 'museums', 'viewpoints', 'kid-friendly'], 'Griffith Park', 'central', 1, 34.1184341, -118.3003935, null, 120, 'mixed'),
  ('los-angeles', 'Santa Monica Pier', 'landmark', array['landmarks', 'viewpoints', 'kid-friendly'], 'Santa Monica', 'nearby', 2, 34.0082821, -118.4987585, null, 90, 'outdoor'),
  ('los-angeles', 'Getty Center', 'museum', array['museums', 'viewpoints', 'kid-friendly'], 'Brentwood', 'nearby', 3, 34.078, -118.4741, null, 180, 'mixed'),
  ('los-angeles', 'The Broad', 'museum', array['museums'], 'Downtown', 'central', 4, 34.05447, -118.25056, null, 120, 'indoor'),
  ('los-angeles', 'Walt Disney Concert Hall', 'landmark', array['landmarks', 'low-cost-free'], 'Downtown', 'central', 5, 34.05535, -118.24985, null, 60, 'mixed'),
  ('los-angeles', 'Hollywood Walk of Fame', 'landmark', array['landmarks', 'low-cost-free'], 'Hollywood', 'central', 6, 34.1016, -118.3269, null, 60, 'outdoor'),
  ('los-angeles', 'TCL Chinese Theatre', 'landmark', array['landmarks'], 'Hollywood', 'central', 7, 34.102, -118.3409, null, 60, 'mixed'),
  ('los-angeles', 'Hollywood Sign Viewpoint at Lake Hollywood Park', 'viewpoint', array['landmarks', 'viewpoints', 'low-cost-free'], 'Hollywood Hills', 'central', 8, 34.1269, -118.3268, null, 60, 'outdoor'),
  ('los-angeles', 'Venice Canals', 'neighborhood', array['neighborhoods', 'viewpoints', 'low-cost-free'], 'Venice', 'nearby', 9, 33.9849, -118.4674, null, 75, 'outdoor'),
  ('los-angeles', 'Getty Villa', 'museum', array['museums', 'viewpoints'], 'Pacific Palisades', 'nearby', 10, 34.0459, -118.5648, null, 150, 'mixed'),
  ('los-angeles', 'Los Angeles County Museum of Art', 'museum', array['museums'], 'Miracle Mile', 'central', 11, 34.0638, -118.3592, null, 150, 'indoor'),
  ('los-angeles', 'La Brea Tar Pits', 'museum', array['museums', 'kid-friendly'], 'Miracle Mile', 'central', 12, 34.0638, -118.3554, null, 90, 'mixed'),
  ('los-angeles', 'Petersen Automotive Museum', 'museum', array['museums', 'kid-friendly'], 'Miracle Mile', 'central', 13, 34.0623, -118.3611, null, 120, 'indoor'),
  ('los-angeles', 'Runyon Canyon Park', 'hike', array['nature', 'viewpoints', 'low-cost-free'], 'Hollywood Hills', 'central', 14, 34.11, -118.35, null, 120, 'outdoor'),
  ('los-angeles', 'El Matador State Beach', 'beach', array['nature', 'viewpoints'], 'Malibu', 'day_trip', 15, 34.0391, -118.8754, null, 120, 'outdoor')
on conflict (destination_slug, lower(name))
do update set
  category = excluded.category,
  tags = excluded.tags,
  area = excluded.area,
  region_distance_tier = excluded.region_distance_tier,
  sort_order = excluded.sort_order,
  latitude = excluded.latitude,
  longitude = excluded.longitude,
  google_place_id = excluded.google_place_id,
  typical_duration_minutes = excluded.typical_duration_minutes,
  indoor_outdoor = excluded.indoor_outdoor,
  updated_at = now();
