create table if not exists public.google_places_api_calls (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  sku text not null check (sku in ('autocomplete', 'details')),
  called_at timestamptz not null default now()
);

create index if not exists idx_google_places_api_calls_sku_date
  on public.google_places_api_calls (sku, called_at desc);

create index if not exists idx_google_places_api_calls_user_date
  on public.google_places_api_calls (user_id, called_at desc);

alter table public.google_places_api_calls enable row level security;

grant all on public.google_places_api_calls to service_role;
grant usage, select on sequence public.google_places_api_calls_id_seq to service_role;

alter table public.trips
  add column if not exists destination_latitude double precision,
  add column if not exists destination_longitude double precision;
