create table if not exists public.ai_destination_transit_hubs (
  id bigint generated by default as identity primary key,
  destination_slug text not null,
  name text not null,
  hub_type text not null,
  iata_code text,
  latitude double precision not null,
  longitude double precision not null,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint ai_destination_transit_hubs_hub_type_valid
    check (hub_type in ('airport', 'train_station', 'bus_terminal', 'ferry_terminal')),
  constraint ai_destination_transit_hubs_name_not_blank
    check (btrim(name) <> ''),
  constraint ai_destination_transit_hubs_latitude_valid
    check (latitude between -90 and 90),
  constraint ai_destination_transit_hubs_longitude_valid
    check (longitude between -180 and 180)
);

create index if not exists idx_ai_destination_transit_hubs_slug
  on public.ai_destination_transit_hubs (destination_slug);

alter table public.ai_destination_transit_hubs enable row level security;

grant all on public.ai_destination_transit_hubs to service_role;

grant usage, select on sequence public.ai_destination_transit_hubs_id_seq to service_role;

insert into public.ai_destination_transit_hubs
  (destination_slug, name, hub_type, iata_code, latitude, longitude, sort_order)
values
  ('new-york-city', 'John F. Kennedy International Airport', 'airport', 'JFK', 40.6413111, -73.7781391, 1),
  ('new-york-city', 'LaGuardia Airport', 'airport', 'LGA', 40.7769271, -73.8739659, 2),
  ('new-york-city', 'Newark Liberty International Airport', 'airport', 'EWR', 40.6895314, -74.1744624, 3),
  ('new-york-city', 'Penn Station (Moynihan Train Hall)', 'train_station', null, 40.7505671, -73.9934387, 4),
  ('new-york-city', 'Port Authority Bus Terminal', 'bus_terminal', null, 40.7569545, -73.9902627, 5),
  ('los-angeles', 'Los Angeles International Airport', 'airport', 'LAX', 33.9415889, -118.40853, 1),
  ('los-angeles', 'Hollywood Burbank Airport', 'airport', 'BUR', 34.1983122, -118.3574036, 2),
  ('los-angeles', 'Long Beach Airport', 'airport', 'LGB', 33.8177202, -118.1516067, 3),
  ('los-angeles', 'Union Station', 'train_station', null, 34.0561689, -118.2365331, 4),
  ('toronto', 'Toronto Pearson International Airport', 'airport', 'YYZ', 43.6777176, -79.6248197, 1),
  ('toronto', 'Billy Bishop Toronto City Airport', 'airport', 'YTZ', 43.6284687, -79.3961528, 2),
  ('toronto', 'Union Station', 'train_station', null, 43.6452599, -79.3805991, 3),
  ('banff-national-park', 'Calgary International Airport', 'airport', 'YYC', 51.1215031, -114.0076156, 1),
  ('banff-national-park', 'Banff Bus Depot', 'bus_terminal', null, 51.1783629, -115.5721545, 2),
  ('iceland', 'Keflavík International Airport', 'airport', 'KEF', 63.9849858, -22.6056483, 1),
  ('iceland', 'Reykjavík Domestic Airport', 'airport', 'RKV', 64.1299652, -21.9405643, 2),
  ('iceland', 'BSÍ Bus Terminal', 'bus_terminal', null, 64.1386874, -21.9333635, 3),
  ('iceland', 'Seyðisfjörður Ferry Terminal', 'ferry_terminal', null, 65.2609073, -14.0088003, 4);
