create table if not exists public.trip_transit_points (
  id bigint generated by default as identity primary key,
  trip_id bigint not null references public.trips(id) on delete cascade,
  kind text not null,
  name text not null,
  latitude double precision not null,
  longitude double precision not null,
  google_place_id text,
  event_time time,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint trip_transit_points_kind_valid
    check (kind in ('arrival', 'departure')),
  constraint trip_transit_points_name_not_blank
    check (btrim(name) <> ''),
  constraint trip_transit_points_latitude_valid
    check (latitude between -90 and 90),
  constraint trip_transit_points_longitude_valid
    check (longitude between -180 and 180)
);

create unique index if not exists idx_trip_transit_points_trip_kind_unique
  on public.trip_transit_points (trip_id, kind);

alter table public.trip_transit_points enable row level security;

grant all on public.trip_transit_points to service_role;

grant usage, select on sequence public.trip_transit_points_id_seq to service_role;
