create table if not exists public.google_routes_api_calls (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  called_at timestamptz not null default now()
);

create index if not exists idx_google_routes_api_calls_user_date
  on public.google_routes_api_calls (user_id, called_at desc);

alter table public.google_routes_api_calls enable row level security;

grant all on public.google_routes_api_calls to service_role;
grant usage, select on sequence public.google_routes_api_calls_id_seq to service_role;
